### ISSUE TITLE
Add Hawthorn Asylum to the list of locations

### ISSUE THREAD

**Issue by lindsaykwardell** [jlengstorf/snack.tips#1]
Seems like a good place to add to the map.

https://en.wikipedia.org/wiki/Hawthorne_Asylum

**Comment by lindsaykwardell** [comment]
Not sure how you're generating the URLs, here's a way-too-long URL to Google Maps: https://www.google.com/maps/place/Hawthorne+Asylum/@45.51279,-122.6574774,17z/data=!3m1!5s0x5495a09fee660f77:0xbc5fa54f5dd94989!4m5!3m4!1s0x5495a194fcf9833f:0xa4c794d774bc3d84!8m2!3d45.51279!4d-122.6552887

**Comment by jlengstorf** [comment]
added! thank you! https://snack.tips/portland/hawthorne-asylum
